# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Grønt Napp
email: raae@bgraphic.no
description: > # this means to ignore newlines until "baseurl:"
  Grønt Napp hjelper deg å velge bærekraftig sjømat.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://grøntnapp.no" # the base hostname & protocol for your site
permalink: pretty
ranking:
  description: >
    Listen er laget av Marinbiologene basert på en kombinasjon av WWFs sjømatguide og informasjon fra ICES (Det internasjonale havforskerrådet) og MSC (Marine Stewardship Council).
  scale:
    - Green:
        title: Grønn
        description: Artene høstes på en bærekraftig måte og kan spises med god samvittighet.
    - Orange:
        title: Oransj
        description: Artene høstes stort sett på en bærekraftig måte. Fangstmetoder og områder kan være av betydning for miljøvennlighet. Se detaljopplysninger for arten.
    - Red:
        title: Rød
        description: Artene høstes på en bærekraftig måte og kan spises med god samvittighet.
ranking_climate:
  description: >
    Klimavalgvurderingene er basert på Grønn Hverdags opplysninger om utslipp av klimagasser.
  scale:
    - Good:
        title: Godt klimavalg
        description: Fangst og transport av disse artene er relativt klimavennlig.
    - Ok:
        title: Ok klimavalg
        description: Fangst og transport av disse artene er litt mindre klimavennlig.
    - Bad:
        title: Dårlig klimavalg
        description: Fangst og transport av disse artene er lite klimavennlig.
collections:
  species:
    output: false
