---
title: Grønt Napp
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  species:
    title: Species
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: species
  values:
    image:
      file: 
      caption: 
    latin: 
    synonyms: 
    slogan:
      content: 
      attribution: 
    alert:
      content: 
      type: 
    ranking: 
    ranking_climate: 
    labels: []
    sources: []
email: raae@bgraphic.no
description: Spis bærekraftig sjømat med god samvittighet!
baseurl: ''
url: http://grøntnapp.no
permalink: pretty
