---
title: Grønt Napp
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  species:
    title: Species
    output: false
  uploads:
    title: Uploads
    output: true
email: raae@bgraphic.no
description: 'Spis bærekraftig sjømat med god samvittighet!

'
baseurl: ''
url: http://grøntnapp.no
permalink: pretty
