---
title: Grønt Napp
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  species:
    title: Species
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: species
  values:
    latin: 
    slogan: 
    alert: 
    ranking: 
    ranking_climate: 
    labels: []
    sources: []
email: raae@bgraphic.no
description: Spis bærekraftig sjømat med god samvittighet!
baseurl: ''
url: http://grøntnapp.no
permalink: pretty
